# Generated by Django 5.0.7 on 2024-09-07 01:09

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('community', models.CharField(blank=True, choices=[('Ahinkrom', 'Ahinkrom'), ('Mill Village', 'Mill Village'), ('Edumasi', 'Edumasi')], max_length=15, null=True)),
                ('house_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user_name', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('user_idnum', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('user_phone_number', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('user_community', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('user_house_number', models.CharField(blank=True, editable=False, max_length=15, null=True)),
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=20)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('time_approved', models.DateTimeField(blank=True, null=True)),
                ('work_date', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_jobs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-time_added'],
            },
        ),
    ]
