# Generated by Django 5.0 on 2024-09-20 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='job',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='job',
            name='rating',
        ),
    ]
