# Generated by Django 5.0 on 2024-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_house_number_alter_job_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
