# Generated by Django 5.0 on 2024-10-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_job_id_alter_job_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_idnum',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
