# Generated by Django 5.0.7 on 2024-09-07 01:07

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('phone_number', models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. Enter a valid Ghanaian phone number.', max_length=20, unique=True, validators=[accounts.validators.validate_phone_number])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('community', models.CharField(choices=[('Ahinkrom', 'Ahinkrom'), ('Mill Village', 'Mill Village'), ('Edumasi', 'Edumasi')], max_length=20)),
                ('house_number', models.CharField(max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='account_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='account_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['user_id'],
            },
        ),
    ]
