# Generated by Django 5.0.7 on 2024-09-17 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expiration_time',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
