# Generated by Django 5.0 on 2024-09-20 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otp_is_verified_remove_otp_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPResendTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
