# Generated by Django 5.0 on 2024-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpresendtracker_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpresendtracker',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
