# Generated by Django 5.0 on 2024-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpresendtracker_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpresendtracker',
            name='prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
