# Generated by Django 5.0 on 2024-09-29 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_otpresendtracker_prefix_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpresendtracker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
