# Generated by Django 5.0 on 2024-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='request_id',
        ),
        migrations.AddField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
