# Generated by Django 5.0 on 2024-09-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
