# Generated by Django 5.0 on 2024-09-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otp_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp',
        ),
    ]
