# Generated by Django 5.0 on 2024-10-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_otp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(max_length=20),
        ),
    ]
