# Generated by Django 5.0 on 2024-10-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
